### ISSUE TITLE
Added to awesome-go!

### ISSUE THREAD

**Issue by fzipi** [bykof/gostradamus#1]
Hey!

I added your mod to the awesome-go. Maybe you want to add [![Mentioned in Awesome Go](https://awesome.re/mentioned-badge.svg)](https://github.com/avelino/awesome-go) or [![Mentioned in Awesome Go](https://awesome.re/mentioned-badge-flat.svg)](https://github.com/avelino/awesome-go) here.

**Comment by bykof** [comment]
Sound great! thank you for that! i will :)

**Comment by bykof** [comment]
done!
