### ISSUE TITLE
Getting issue "The system cannot find the path specified" while finding current datetime in given timezone in windows

### ISSUE THREAD

**Issue by viveksatasiya** [bykof/gostradamus#2]
Hello,

I am getting an issue "The system cannot find the path specified" while finding current datetime in given timezone in windows. here is the code.
![error](https://user-images.githubusercontent.com/15060226/122969670-85f10b80-d3aa-11eb-9669-2f48a44e0431.jpeg)

`from_date := gostradamus.NowInTimezone(gostradamus.AsiaKolkata)`

This code works perfectly in linux but getting an error in windows.

Please let me know if I am making any mistakes.

Thanks in advance.

**Comment by bykof** [comment]
This looks really strange... actually there shouldn't be a problem. I googled this error and couldn't find any hint.
This looks to me like you haven't installed it correctly, please check your go.mod and probably reinstall it properly. Sorry, but I can't give you more advice, the error is too ambiguous :/

**Comment by viveksatasiya** [comment]
Here is the code of main.go file.
`package main`

`import "github.com/bykof/gostradamus"`

`func main() {`
	`toTime := gostradamus.NowInTimezone(gostradamus.AsiaKolkata)`
	`to := toTime.Format("YYYY-MM-DD HH:mm")`
	`println(to)`
`}`

Here is the go.mod file.

`module main`
`go 1.16`
`require github.com/bykof/gostradamus v1.0.4 // indirect`

I am building windows exe on ubuntu machine using following command.
`GOOS=windows GOARCH=amd64 go build`

I have also attached the screenshot of an error.
![screenshot](https://user-images.githubusercontent.com/15060226/124228877-71d7a780-db2a-11eb-891d-36dbcfc04080.png)

**Comment by viveksatasiya** [comment]
Resolved issue. Added `import _ "time/tzdata"` in main file.

We need to add timezone data into our binary for windows.

Thanks for your support.
